---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: unik-admission-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-services
rules:
  - apiGroups: ['']
    resources: ['services']
    verbs: ['get', 'watch', 'list']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-services-binding
subjects:
  - kind: ServiceAccount
    name: unik-admission-controller
roleRef:
  kind: ClusterRole
  name: read-services
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secrets-full-access
rules:
  - apiGroups: ['']
    resources: ['secrets']
    verbs: ['get', 'list', 'watch', 'create', 'update', 'patch', 'delete']
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secrets-full-access-binding
subjects:
  - kind: ServiceAccount
    name: unik-admission-controller
roleRef:
  kind: Role
  name: secrets-full-access
  apiGroup: rbac.authorization.k8s.io
