---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: unik-admission-controller
  annotations:
    cert-manager.io/inject-ca-from: default/unik-admission-controller
webhooks:
  - name: unik-k8s.github.com
    clientConfig:
      service:
        name: unik-admission-controller-webhook
        namespace: default
        port: 8443
        path: "/validate"
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - services
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions: ["v1"]
